# Generated by Django 4.0.4 on 2022-07-07 09:56

from django.db import migrations, models
import django.db.models.deletion
import languages.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_created_at_language_updated_at'),
        ('block', '0004_alter_block_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='content',
        ),
        migrations.RemoveField(
            model_name='block',
            name='language',
        ),
        migrations.RemoveField(
            model_name='block',
            name='status',
        ),
        migrations.CreateModel(
            name='blockContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('language', models.ForeignKey(default=languages.models.get_language, null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
