# Generated by Django 4.0.4 on 2022-07-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0006_remove_block_title_remove_blockcontent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockcontent',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='block.block'),
        ),
    ]
