# Generated by Django 4.0.4 on 2022-07-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0007_blockcontent_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blockContent',
        ),
    ]
