# Generated by Django 4.0.4 on 2022-07-07 12:08

from django.db import migrations, models
import django.db.models.deletion
import languages.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_created_at_language_updated_at'),
        ('block', '0008_delete_blockcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='blockContent',
            fields=[
                ('blockContentId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='block.block')),
                ('language', models.ForeignKey(default=languages.models.get_language, null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
