# Generated by Django 4.0.4 on 2022-05-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute', '0002_alter_attributefields_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='options',
            fields=[
                ('optionId', models.AutoField(primary_key=True, serialize=False)),
                ('customOption', models.CharField(max_length=100, unique=True, verbose_name='Custom Option')),
                ('customOptionValue', models.CharField(max_length=100, unique=True, verbose_name='Custom Option Value')),
                ('sortOrder', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('isDefault', models.BooleanField(default=False, verbose_name='Is Default')),
                ('fieldId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attributefields')),
            ],
        ),
    ]
