# Generated by Django 4.0.4 on 2022-05-31 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute_option', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='customOptionValue',
        ),
    ]
