# Generated by Django 4.0.4 on 2022-06-01 08:24

from django.db import migrations, models
import django.db.models.deletion
import languages.models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('attribute_option', '0002_remove_options_customoptionvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionTranslate',
            fields=[
                ('optionTranslateId', models.AutoField(primary_key=True, serialize=False)),
                ('optionsLabel', models.CharField(max_length=10, unique=True, verbose_name='Option Label')),
                ('languageId', models.ForeignKey(default=languages.models.get_language, on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('optionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute_option.options')),
            ],
        ),
    ]
