# Generated by Django 4.0.4 on 2022-06-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=25, verbose_name='Last Name')),
                ('profileimage', models.ImageField(upload_to='uploads/')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contactno', models.CharField(max_length=10, verbose_name='Contact No')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('groupId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('isDefault', models.BooleanField(default=False, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
