# Generated by Django 4.0.4 on 2022-06-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20220623_1205'),
    ]

    operations = [
    ]
