# Generated by Django 4.0.4 on 2022-06-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20220623_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinformation',
            name='customergroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.group', verbose_name='Customer Group'),
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='emailVerifyDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='profileimage',
            field=models.ImageField(upload_to='uploads/', verbose_name='Profile Image'),
        ),
    ]
