# Generated by Django 4.0.4 on 2022-06-23 06:46

import customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customerinformation_customergroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinformation',
            name='customergroup',
            field=models.ForeignKey(default=customers.models.get_group, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.group', verbose_name='Customer Group'),
        ),
    ]
