# Generated by Django 4.0.4 on 2022-06-23 06:54

import customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customerinformation_customergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinformation',
            name='customergroup',
            field=models.ForeignKey(default=customers.models.get_group, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.group'),
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('contactNo', models.CharField(max_length=10, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email Id')),
                ('profileImage', models.ImageField(upload_to='images/', verbose_name='Profile Image')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('emailVarificationDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('customerGroup', models.ForeignKey(default=customers.models.get_group, on_delete=django.db.models.deletion.CASCADE, to='customers.group')),
            ],
        ),
    ]
