# Generated by Django 4.0.4 on 2022-06-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customeraddress_isdefault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='isDefault',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
    ]
