# Generated by Django 4.0.4 on 2022-05-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeFields',
            fields=[
                ('attributeId', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('inputType', models.CharField(choices=[('boolean', 'Boolean'), ('checkbox', 'Checkbox'), ('multi-select', 'Multi-select'), ('select', 'Select'), ('radio', 'Radio'), ('textbox', 'Textbox'), ('textarea', 'Textarea')], default='enabled', max_length=15, verbose_name='Input Type')),
                ('sortOrder', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('isRequired', models.BooleanField(default=False, verbose_name='Is Required?')),
            ],
        ),
    ]
