# Generated by Django 4.0.4 on 2022-06-06 06:19

from django.db import migrations, models
import django.db.models.deletion
import languages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeFields',
            fields=[
                ('attributeId', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('inputType', models.CharField(choices=[('boolean', 'Boolean'), ('checkbox', 'Checkbox'), ('multi-select', 'Multi-select'), ('select', 'Select'), ('radio', 'Radio'), ('textbox', 'Textbox'), ('textarea', 'Textarea')], default='enabled', max_length=15, verbose_name='Input Type')),
                ('sortOrder', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('isRequired', models.BooleanField(default=False, verbose_name='Is Required?')),
            ],
        ),
        migrations.CreateModel(
            name='options',
            fields=[
                ('optionId', models.AutoField(primary_key=True, serialize=False)),
                ('customOption', models.CharField(max_length=100, unique=True, verbose_name='Custom Option')),
                ('sortOrder', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('isDefault', models.BooleanField(default=False, verbose_name='Is Default')),
                ('fieldId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomAttributes.attributefields')),
            ],
        ),
        migrations.CreateModel(
            name='OptionTranslate',
            fields=[
                ('optionTranslateId', models.AutoField(primary_key=True, serialize=False)),
                ('optionsLabel', models.CharField(max_length=10, unique=True, verbose_name='Option Label')),
                ('languageId', models.ForeignKey(default=languages.models.get_language, on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('optionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomAttributes.options')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeTranslate',
            fields=[
                ('attributeTranslateId', models.AutoField(primary_key=True, serialize=False)),
                ('fieldLabel', models.CharField(max_length=15, verbose_name='Label')),
                ('fieldId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomAttributes.attributefields')),
                ('languageId', models.ForeignKey(default=languages.models.get_language, on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
