# Generated by Django 4.0.4 on 2022-07-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAttributes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttributeFields',
            new_name='AttributeField',
        ),
    ]
