# Generated by Django 4.0.4 on 2022-07-08 07:03

from django.db import migrations, models
import django.db.models.deletion
import languages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0002_language_created_at_language_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('BannerGroupId', models.AutoField(primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('code', models.CharField(default=None, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerGroupTranslation',
            fields=[
                ('BannerGroupTranslationId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
                ('bannerGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Banner.bannergroup')),
                ('language', models.ForeignKey(default=languages.models.get_language, null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
