# Generated by Django 4.0.4 on 2022-07-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('BannerId', models.AutoField(primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('isFeatured', models.BooleanField()),
                ('bannerGroups', models.ManyToManyField(to='Banner.bannergroup')),
            ],
        ),
        migrations.CreateModel(
            name='BannerTranslation',
            fields=[
                ('BannnerTransId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100)),
                ('content', models.CharField(default=None, max_length=200)),
                ('Banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Banner.banner')),
            ],
        ),
    ]
