# Generated by Django 4.0.4 on 2022-07-11 07:23

from django.db import migrations, models
import django.db.models.deletion
import languages.models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_created_at_language_updated_at'),
        ('Banner', '0003_banner_created_at_banner_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannertranslation',
            name='language',
            field=models.ForeignKey(default=languages.models.get_language, null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
    ]
