# Generated by Django 4.0.4 on 2022-07-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0004_bannertranslation_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('BannerImageId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='bannerImage/', verbose_name='Profile Image')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Banner.banner')),
                ('BannerGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Banner.bannergroup')),
            ],
        ),
    ]
