# Generated by Django 4.0.4 on 2022-07-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0006_alter_banner_options_alter_bannerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(upload_to='bannerImage/', verbose_name='Profile Image'),
        ),
    ]
